### ISSUE TITLE
BottledPoker Error

### ISSUE THREAD

**Issue by DarkJDL** [Celicath/PokerPlayerMod#3]
I got this error twice today; I'll append a list of mods I'm using under the error.

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at ThePokerPlayer.relics.BottledPoker.onLoad(BottledPoker.java:103)
	at ThePokerPlayer.relics.BottledPoker.onLoad(BottledPoker.java:21)
	at basemod.abstracts.CustomSavable.onLoadRaw(CustomSavable.java:40)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.LoadPlayerSaves.Postfix(LoadPlayerSaves.java:66)
	at com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(CardCrawlGame.java:1245)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:801)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
	
	Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (03-07-2022)
 - ModTheSpire (3.27.0)
Mod list:
 - basemod (5.41.0)
 - stslib (2.3.0)
 - OptimizeTheSpire (1.1.0)
 - versiontwocompatible (2.2.5)
 - RelicStats (1.2.2)
 - ShopMod (1.1.2)
 - infinitespire (0.23.0)
 - TheChaser (1.25)
 - betterrewardsmod (4.5.0)
 - Hermit (1.50)
 - ReplayTheSpireMod (1.6.7)
 - HierophantMod (2.0.0)
 - betterThird (1.5)
 - RelicFilterMod (1.0.1)
 - reliquary (0.4.1)
 - superfastmode (1.0.7)
 - thecursed (1.1.10)
 - NecroMod (1.0.0)
 - PokerPlayerMod (1.0.7)
 - MoreChoices (1.0.2)

Otherwise, Good Character, Continue the good work, it's a really fun class to play!

**Comment by Celicath** [comment]
Thanks for the report. I believe this crash happens when you (somehow) remove the cards selected by Bottled Poker from your deck, and then save & load it. It should be fixed in v1.0.8, which I uploaded to the workshop just now.

**Comment by DarkJDL** [comment]
I think that did fix it, It's a bit hard to re-create the conditions that broke it, but I was able to continue the game and it did not crash on continue 👍 
Good Job! Thanks!
